import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@/commons/styles/reset.css"; // 글로벌 스타일 커스텀 처리 및 초기화 처리 css
import Layout from "@/commons/layout";
import ApolloSetting from "@/commons/settings/apollo-setting";
import DeviceSetting from "@/commons/settings/device-setting";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const localFontSet = localFont({
  variable: "--suit",
  src: "./fonts/SUIT-Variable.woff2",
});

interface IChildrenType {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IChildrenType) {
  return (
    <html lang="ko">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body className={`${localFontSet.variable} antialiased`}>
        <ApolloSetting>
          <DeviceSetting>
            <Layout>{children}</Layout>
          </DeviceSetting>
        </ApolloSetting>
      </body>
    </html>
  );
}
